-- DROP
DROP TABLE IF EXISTS users;

-- CREATE
CREATE TABLE IF NOT EXISTS users
(
    id    INT         NOT NULL AUTO_INCREMENT,
    name  VARCHAR(32) NOT NULL,
    email VARCHAR(32) NOT NULL,
    PRIMARY KEY (id)
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin;